export const INCREASE_CHEESE_BURGER = "INCREASE_CHEESE_BURGER";
export const INCREASE_VEGCHEESE_BURGER = "INCREASE_VEGCHEESE_BURGER";
export const INCREASE_BURGER_WITH_FRIES = "INCREASE_BURGER_WITH_FRIES";

export const DECREASE_CHEESE_BURGER = "DECREASE_CHEESE_BURGER";
export const DECREASE_VEGCHEESE_BURGER = "DECREASE_VEGCHEESE_BURGER";
export const DECREASE_BURGER_WITH_FRIES = "DECREASE_BURGER_WITH_FRIES";

export const CART_ITEM_REQUEST = "CART_ITEM_REQUEST";
export const CART_ITEM_SUCCESS = "CART_ITEM_SUCCESS";
export const CART_ITEM_FAIL = "CART_ITEM_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
